# Generated by Django 6.0.5 on 2026-05-27 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('content', models.TextField()),
                ('author', models.CharField(default='Orbinexglobal Team', max_length=100)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='blogs/')),
                ('banner_image_url', models.URLField(blank=True, help_text='Fallback external URL', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seo_title', models.CharField(blank=True, max_length=150, null=True)),
                ('seo_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('image_url', models.URLField(blank=True, help_text='Fallback external image URL', null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='certifications/')),
                ('logo_url', models.URLField(blank=True, help_text='Fallback external URL', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('certificate_authority', models.CharField(blank=True, max_length=150, null=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExportCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country_code', models.CharField(help_text='e.g. US, AE, GB', max_length=5)),
                ('flag_emoji', models.CharField(help_text='e.g. 🇺🇸', max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Export Countries',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HomepageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(blank=True, max_length=250, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('image_url', models.URLField(blank=True, help_text='Fallback external URL', null=True)),
                ('link', models.CharField(default='/products', max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=150)),
                ('role', models.CharField(default='Importer', max_length=100)),
                ('review', models.TextField()),
                ('rating', models.IntegerField(default=5, help_text='Rating between 1 and 5')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('profile_image_url', models.URLField(blank=True, help_text='Fallback external URL', null=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('description', models.TextField()),
                ('origin', models.CharField(default='India', max_length=100)),
                ('quality_grade', models.CharField(default='A Grade (Premium Export Quality)', max_length=50)),
                ('moq', models.CharField(help_text='Minimum Order Quantity, e.g. 10 Metric Tons', max_length=100)),
                ('packaging_type', models.CharField(help_text='e.g. Corrugated Boxes, Mesh Bags, Vacuum Sealed', max_length=150)),
                ('shelf_life', models.CharField(help_text='e.g. 3 Months at 5°C', max_length=100)),
                ('export_availability', models.BooleanField(default=True)),
                ('base_price_inr', models.DecimalField(decimal_places=2, help_text='Base price in INR per unit', max_digits=12, max_length=15)),
                ('price_unit', models.CharField(default='Metric Ton', help_text='e.g. kg, Metric Ton, Box', max_length=30)),
                ('primary_image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('primary_image_url', models.URLField(blank=True, help_text='Fallback external primary image URL', null=True)),
                ('meta_title', models.CharField(blank=True, max_length=150, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.category')),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('company', models.CharField(blank=True, max_length=150, null=True)),
                ('message', models.TextField()),
                ('quantity', models.CharField(blank=True, help_text='e.g. 20 Metric Tons', max_length=100, null=True)),
                ('shipping_terms', models.CharField(blank=True, help_text='e.g. FOB, CIF, CNF', max_length=50, null=True)),
                ('destination_port', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('new', 'New/Unread'), ('contacted', 'Contacted/In Progress'), ('completed', 'Completed/Closed'), ('spam', 'Spam/Junk')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('target_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.product')),
            ],
            options={
                'verbose_name_plural': 'Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/additional/')),
                ('image_url', models.URLField(blank=True, help_text='Fallback external URL', null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='api.product')),
            ],
        ),
    ]
