# Generated by Django 5.0 on 2026-06-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_galleryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagebanner',
            name='link',
            field=models.CharField(blank=True, default='/products', max_length=100, null=True),
        ),
    ]
